version: '3'

services:
 ner:
  build: "./Server"
  restart: always
  volumes:
   - ./Server:/apps/ner
   - ./model:/model
  entrypoint: /apps/ner/docker-entry.sh 

 ocr:
  build: "./INSUR"
  restart: always
  volumes:
   - ./INSUR:/apps/ocr
   - ./model:/model
  ports:
   - 8090:8080
   - 5055:5005
  entrypoint: /apps/ocr/docker-entry.sh
